name: Open Release PR (develop → master, semver auto)

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  open_release_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
      - name: Fetch remotes & tags
        run: |
          git fetch --prune origin
          git fetch --tags origin

      - name: Switch to develop as working base
        run: |
          git checkout -B develop origin/develop

      - name: Compute next version & notes (dry run)
        id: ver
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          fetch_all_tags: true
          release_branches: ".*"
          tag_prefix: "v"

      - name: Create and push release branch from develop
        run: |
          REL="release/${{ steps.ver.outputs.new_tag }}"
          git checkout -B "$REL" origin/develop
          git push -u origin "$REL" --force-with-lease

      - name: Open PR with repo-sync/pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: "release/${{ steps.ver.outputs.new_tag }}"
          destination_branch: "master"
          pr_title: "chore(master): release ${{ steps.ver.outputs.new_version }}"
          pr_body: |
            :robot: I have created a release *beep* *boop*

            ## Compare
            https://github.com/${{ github.repository }}/compare/master...develop

            > Next tag (computed): ${{ steps.ver.outputs.new_tag }}

            ---
            This PR was generated by a Release-Please-like workflow (semver from Conventional Commits).
          pr_label: "release,autorelease: pending"
