name: Open Release PR (develop → master, semver auto)

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  open_release_pr:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout fora do develop e com histórico + tags completos
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Fetch remotes & tags
        run: |
          git fetch --prune origin
          git fetch --tags origin

      # 2) Baseia trabalho na ponta do develop (local, sem publicar ainda)
      - name: Create temp release branch from develop
        run: |
          git checkout -B release/work origin/develop

      # 3) Calcula PRÓXIMA versão (SemVer) e changelog desde a última tag (dry run)
      #    -> NÃO cria tag; só computa new_tag/new_version/previous_tag/changelog
      - name: Compute next version & notes (dry run)
        id: ver
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          fetch_all_tags: true
          release_branches: ".*" # calcula versão mesmo fora de master/main
          tag_prefix: "v"

      # 4) Gera um arquivo de notas para a PR (sem scripts)
      - name: Write RELEASE_NOTES.md
        uses: DamianReeves/write-file-action@v1.3
        with:
          path: RELEASE_NOTES.md
          contents: |
            ## ${{ steps.ver.outputs.new_tag }}

            ${{ steps.ver.outputs.changelog }}

      # (Opcional) grava a versão calculada num arquivo simples para garantir diff
      - name: Write VERSION file
        uses: DamianReeves/write-file-action@v1.3
        with:
          path: VERSION
          contents: "${{ steps.ver.outputs.new_version }}"

      # 5) Cria a PR release/vX.Y.Z → master
      - name: Create PR (RP-like body)
        uses: peter-evans/create-pull-request@v7
        with:
          branch: "release/${{ steps.ver.outputs.new_tag }}" # ex.: release/v1.4.0
          base: "master"
          title: "chore(master): release ${{ steps.ver.outputs.new_version }}"
          labels: "release,autorelease: pending"
          commit-message: "chore(release): v${{ steps.ver.outputs.new_version }} [skip ci]"
          add-paths: |
            RELEASE_NOTES.md
            VERSION
          delete-branch: true
          body: |
            :robot: I have created a release *beep* *boop*

            ## [${{ steps.ver.outputs.new_tag }}](
            https://github.com/${{ github.repository }}/compare/${{ steps.ver.outputs.previous_tag }}...${{ steps.ver.outputs.new_tag }})

            ${{ steps.ver.outputs.changelog }}

            ---
            This PR was generated by a Release-Please-like workflow (semver from Conventional Commits).

      - name: Cleanup local temp branch
        if: always()
        run: |
          git checkout master
          git branch -D release/work || true
