name: release-please
on:
  push:
    branches: [master] # ou main
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple # node, java, python, go, rust, etc. se preferir
          bump-minor-pre-major: true # (opcional) antes de v1.0.0, feat => minor
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"docs","section":"Docs","hidden":false},
              {"type":"refactor","section":"Refactors","hidden":false},
              {"type":"perf","section":"Performance","hidden":false},
              {"type":"chore","section":"Chores","hidden":false}
            ]
