name: release-please
on:
  push:
    branches: [master] # ou main
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          target-branch: master
          release-type: simple
          config-file: ./.github/files/release-please-config.json
