# .github/workflows/tag-and-release.yml
name: Tag & GitHub Release
on:
  pull_request:
    types: [closed]
    branches: [master]

permissions:
  contents: write

jobs:
  tag_and_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # Calcula próxima versão (SemVer) a partir dos commits desde a última tag e cria a tag vX.Y.Z
      - name: Bump & create tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"

      # Cria a GitHub Release com notas automáticas
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          generate_release_notes: true
